const barcodeItems = [
  {
    id: 1,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'Code128 auto',
    navigator: 'VCard',
  },
  {
    id: 2,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'Code128 A',
    navigator: 'Message',
  },
  {
    id: 3,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'Code128 B',
    navigator: 'Email',
  },
  {
    id: 4,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'Code128 C',
    navigator: 'Text',
  },
  {
    id: 5,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'EAN13',
    navigator: 'Phone',
  },
  {
    id: 6,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'EAN8',
    navigator: 'Link',
  },
  {
    id: 7,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'UPC',
    navigator: 'Contact',
  },
  {
    id: 8,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'CODE39',
    navigator: 'Wifi',
  },
  {
    id: 9,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'ITF14',
    navigator: 'Bitcoin',
  },
  {
    id: 10,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'ITF',
    navigator: 'SocialMedia',
  },
  {
    id: 11,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'MSI',
    navigator: 'pdf',
  },
  {
    id: 12,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'MSI10',
    navigator: 'MP3',
  },
  {
    id: 13,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'MSI11',
    navigator: 'Application',
  },
  {
    id: 14,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'MSI1010',
    navigator: 'Application',
  },
  {
    id: 15,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'MSI1110',
    navigator: 'Application',
  },
  {
    id: 16,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'PHARMACODE',
    navigator: 'Application',
  },
];
export default barcodeItems;
