const barcodeItems = [
  {
    id: 1,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'Code128 auto',
    navigator: 'Code128 auto',
  },
  {
    id: 2,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'Code128 A',
    navigator: 'Code128 A',
  },
  {
    id: 3,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'Code128 B',
    navigator: 'Code128 B',
  },
  {
    id: 4,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'Code128 C',
    navigator: 'Code128 C',
  },
  {
    id: 5,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'EAN13',
    navigator: 'EAN13',
  },
  {
    id: 6,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'EAN8',
    navigator: 'EAN8',
  },
  {
    id: 7,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'UPC',
    navigator: 'UPC',
  },
  {
    id: 8,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'CODE39',
    navigator: 'CODE39',
  },
  {
    id: 9,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'ITF14',
    navigator: 'ITF14',
  },
  {
    id: 10,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'ITF',
    navigator: 'ITF',
  },
  {
    id: 11,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'MSI',
    navigator: 'MSI',
  },
  {
    id: 12,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'MSI10',
    navigator: 'MSI10',
  },
  {
    id: 13,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'MSI11',
    navigator: 'MSI11',
  },
  {
    id: 14,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'MSI1010',
    navigator: 'MSI1010',
  },
  {
    id: 15,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'MSI1110',
    navigator: 'MSI1110',
  },
  {
    id: 16,
    image: require('./assets/images/barcode.png'),
    width: 35,
    height: 35,
    text: 'PHARMACODE',
    navigator: 'PHARMACODE',
  },
];
export default barcodeItems;
