const qrcodeItems = [
  {
    id: 1,
    image: require('./assets/images/meCard.png'),
    width: 35,
    height: 35,
    text: 'VCard',
    navigator: 'VCard',
  },
  {
    id: 2,
    image: require('./assets/images/message.png'),
    width: 35,
    height: 35,
    text: 'Mesaj',
    navigator: 'Message',
  },
  {
    id: 3,
    image: require('./assets/images/email.png'),
    width: 35,
    height: 35,
    text: 'Email',
    navigator: 'Email',
  },
  {
    id: 4,
    image: require('./assets/images/text.png'),
    width: 35,
    height: 35,
    text: 'Metin',
    navigator: 'Text',
  },
  {
    id: 5,
    image: require('./assets/images/telephone.png'),
    width: 35,
    height: 35,
    text: 'Telefon',
    navigator: 'Phone',
  },
  {
    id: 6,
    image: require('./assets/images/unlink.png'),
    width: 35,
    height: 35,
    text: 'Link',
    navigator: 'Link',
  },
  {
    id: 8,
    image: require('./assets/images/wifi.png'),
    width: 35,
    height: 35,
    text: 'Wifi',
    navigator: 'Wifi',
  },
  {
    id: 9,
    image: require('./assets/images/bitcoin.png'),
    width: 35,
    height: 35,
    text: 'Bitcoin',
    navigator: 'Bitcoin',
  },
  // {
  //   id: 10,
  //   image: require('./assets/images/social-media.png'),
  //   width: 35,
  //   height: 35,
  //   text: 'Sosyal Medya',
  //   navigator: 'SocialMedia',
  // },
  {
    id: 11,
    image: require('./assets/images/pdf-file.png'),
    width: 35,
    height: 35,
    text: 'PDF',
    navigator: 'pdf',
  },
  {
    id: 12,
    image: require('./assets/images/mp3.png'),
    width: 35,
    height: 35,
    text: 'MP3',
    navigator: 'MP3',
  },
  {
    id: 13,
    image: require('./assets/images/application.png'),
    width: 35,
    height: 35,
    text: 'Uygulama Mağazası',
    navigator: 'Application',
  },
];
export default qrcodeItems;
